on: [push]
jobs:
  build-and-deploy:
    env:
      REGISTRY_URL: kapasrijkubacr.azurecr.io
      SERVICE_NAME: kpjavakubernetes  
      NAMESPACE: kpjavakubernetes  
      IMAGE_NAME: kpjavakubernetes
      APP_NAME: $(SERVICE_NAME)_
      SECRET_NAME: kpjavakubernetesdockerauth
      system.debug: 'true'

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: kapasrijkubacr.azurecr.io
        username: 'kapasrijkubacr'
        password: 's+Hpaz1jpJFcwmq647n+IpLepCicg4G3'
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        echo $IMAGE_NAME
        echo $DOCKER_CONFIG
        cat $DOCKER_CONFIG/config.json
        docker build "$GITHUB_WORKSPACE/node/plain/container/Application" -f  "node/plain/container/Application/Dockerfile" -t  $REGISTRY_URL/$IMAGE_NAME
        docker push $REGISTRY_URL/$IMAGE_NAME
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: kpjavakubernetes_b549e
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep $NAMESPACE | wc -l`
        echo $namespacePresent
        echo $NAMESPACE
        echo $KUBECONFIG
        cat $KUBECONFIG
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace $NAMESPACE`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: kpjavakubernetes
        container-registry-url: kapasrijkubacr.azurecr.io
        container-registry-username: 'kapasrijkubacr'
        container-registry-password: 's+Hpaz1jpJFcwmq647n+IpLepCicg4G3'
        secret-name: kpjavakubernetesdockerauth
       
    - name: Generate Kubernetes Manifest file
      id: manifest-creation
      run: |
        echo  "apiVersion: apps/v1beta1
              kind: Deployment
              metadata:
                name: "$APP_NAME"
              spec:
                replicas: 2
                template:
                  metadata:
                    labels:
                      app: "$APP_NAME"
              spec:
                containers:
                  - name: "$APP_NAME"
                    image: "$REGISTRY_URL/$IMAGE_NAME"
                    ports:
                    - containerPort: 8080
                  
                  

                apiVersion: v1
                kind: Service
                metadata:
                    name: "$APP_NAME"
                    labels:
                        app: "$APP_NAME"
                spec:
                    type: LoadBalancer
                    ports:
                    - port: 8080
                      targetPort: http
                      protocol: TCP
                      name: http
                    selector:
                        app: "$APP_NAME"
                        
                 "  > manifest_.yml


    - uses: azure/k8s-deploy@v1
      with:
        namespace: $NAMESPACE
        manifests: |
          .yml }}}
        images: |
          $REGISTRY_URL/$IMAGE_NAME:abc
        imagepullsecrets: |
          $SECRET_NAME
